mxonline/MxOnlin/apps/users/urls.py
# _*_ coding:utf-8 _*_
__author__='xuyijie'
__date__='2018/2/24 下午2:36'


from django.conf.urls import url


from .views import UserInfoView,UploadImageView,ResetPwdView,SendEmailCodeView


urlpatterns = [
    url(r'^list/$', UserInfoView.as_view(),name='user_list'),
    url(r'^image/upload/$', UploadImageView.as_view(),name='image_upload'),
    url(r'^update/pwd/$', ResetPwdView.as_view(),name='update_pwd'),
    #发送邮箱验证码
    url(r'^send_emailcode/$', SendEmailCodeView.as_view(),name='send_emailcode'),
]

mxonline/MxOnlin/apps/courses/models.py
# _*_ encoding:utf-8 _*_
from __future__ import unicode_literals
from datetime import datetime

from django.db import models


from organization.models import CourseOrg,Teacher

# Create your models here.


class Course(models.Model):
    course_org=models.ForeignKey(CourseOrg,verbose_name=u'课程机构',null=True,blank=True)
    teachers=models.ForeignKey(Teacher,verbose_name=u'授课教师',null=True,blank=True)
    name=models.CharField(max_length=50,verbose_name=u'课程名')
    desc=models.CharField(max_length=300,verbose_name=u'课程描述')
    detail=models.TextField(verbose_name=u'课程详情')
    degree=models.CharField(choices=(('cj',u'初级'),('zj',u'中级'),('gj',u'高级')),max_length=2)
    learn_times=models.IntegerField(default=0,verbose_name=u'学习时常（分钟数）')
    students=models.IntegerField(default=0,verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name=u'收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name=u'封面图', max_length=100)
    click_nums=models.IntegerField(default=0,verbose_name=u'点击数')
    category=models.CharField(verbose_name='课程类别',max_length=20,default='后端开发')
    tag=models.CharField(default='',verbose_name='课程标签',max_length=10)
    you_need=models.CharField(default='',verbose_name='课程须知',max_length=300,null=True,blank=True)
    teacher_tell = models.CharField(default='', verbose_name='老师告诉你', max_length=300,null=True,blank=True)
    add_time=models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name=u'课程'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return self.name


    #获取课程章节数
    def get_zj_nums(self):
        return self.lesson_set.all().count()


    #学习用户
    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    #获取章节信息
    def get_learn_lesson(self):
        return self.lesson_set.all()


class Lesson(models.Model):
    course=models.ForeignKey(Course,verbose_name=u'课程')
    name=models.CharField(max_length=100,verbose_name=u'章节名')

    class Meta:
        verbose_name=u'章节'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return self.name

        # 获取视频信息
    def get_learn_vedio(self):
        return self.video_set.all()

class Video(models.Model):
    lesson=models.ForeignKey(Lesson,verbose_name=u'章节名')
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    url = models.CharField(max_length=200,verbose_name=u'访问地址',default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name=u'视频'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return self.name

class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'名称')
    download = models.FileField(upload_to='course/resource/%Y/%m',verbose_name=u'资源文件',max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')


    class Meta:
        verbose_name=u'课程资源'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return self.name

mxonline/MxOnlin/apps/organization/models.py
# _*_ encoding:utf-8 _*_
from __future__ import unicode_literals
from datetime import datetime


from django.db import models

# Create your models here.


class CityDict(models.Model):
    name = models.CharField(max_length=20, verbose_name=u'城市')
    desc=models.CharField(max_length=20, verbose_name=u'描述')
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name=u'城市'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return self.name


class CourseOrg(models.Model):
    name=models.CharField(max_length=50,verbose_name=u'机构名称')
    catgory=models.CharField(default='pxjg',max_length=20,choices=(('pxjg','培训机构'),('gx','高校'),('ge','个人')),verbose_name=u'机构类别')
    desc=models.TextField(verbose_name=u'机构描述')
    click_nums=models.IntegerField(verbose_name=u'点击数',default=0)
    fav_nums = models.IntegerField(verbose_name=u'收藏数', default=0)
    image = models.ImageField(upload_to='org/%Y/%m', verbose_name=u'封面图', max_length=100)
    address=models.CharField(max_length=150,verbose_name=u'机构地址')
    city=models.ForeignKey(CityDict,verbose_name=u'所在城市')
    students=models.IntegerField(verbose_name=u'学习人数', default=0)
    course_nums=models.IntegerField(verbose_name=u'课程数', default=0)
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name=u'课程机构'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return self.name

    #获取机构教师数量
    def get_teachers_nums(self):
        return self.teacher_set.all().count()


class Teacher(models.Model):
    org=models.ForeignKey(CourseOrg,verbose_name=u'所属机构')
    name=models.CharField(max_length=50,verbose_name=u'教师名')
    age=models.IntegerField(verbose_name=u'年龄',default=18)
    work_year=models.IntegerField(verbose_name=u'工作年限',default=0)
    work_company=models.CharField(verbose_name=u'就职公司',max_length=50)
    work_position=models.CharField(verbose_name=u'公司职位',max_length=50)
    points=models.CharField(verbose_name=u'教学特点',max_length=50)
    click_nums = models.IntegerField(verbose_name=u'点击数', default=0)
    fav_nums = models.IntegerField(verbose_name=u'收藏数', default=0)
    image=models.ImageField(upload_to='teachers/%Y/%m', verbose_name=u'讲师图像', max_length=100,default='')
    add_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name=u'教师'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return self.name

mxonline/MxOnlin/apps/organization/views.py
# _*_ encoding:utf-8 _*_
from django.shortcuts import render
from django.views.generic import View

from organization.models import CourseOrg,CityDict
from pure_pagination import Paginator, PageNotAnInteger
from django.http import HttpResponse

from .forms import UserAskForm
from operation.models import UserFavorite
from organization.models import Teacher
from courses.models import Course

# Create your views here.


class OrgListView(View):
    def get(self,request):
        all_orgs=CourseOrg.objects.all()
        hot_orgs=all_orgs.order_by('-click_nums')[:3]
        all_citys=CityDict.objects.all()
        # 城市搜索
        city_id = request.GET.get('city', '')
        if city_id:
            all_orgs=all_orgs.filter(city_id=int(city_id))
        # 类别搜索
        category = request.GET.get('ct', '')
        if category:
            all_orgs = all_orgs.filter(catgory=category)
        # 学习人数排序
        sort = request.GET.get('sort', '')
        if sort=='students':
            all_orgs = all_orgs.order_by('-students')
        elif sort=='courses':
        # 课程数量排序
            all_orgs = all_orgs.order_by('-course_nums')
        org_nums = all_orgs.count()
        #课程机构分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(all_orgs, 3,request=request)
        orgs = p.page(page)
        return render(request,'org-list.html',{
            'all_orgs':orgs,
            'all_citys':all_citys,
            'org_nums':org_nums,
            'city_id':city_id,
            'category':category,
            'hot_orgs':hot_orgs,
            'sort':sort,
        })


class UserAskView(View):
    def post(self,request):
        userask_form=UserAskForm(request.POST)
        if userask_form.is_valid():
            userask_form.save(commit=True)
            print 'ffff'
            return HttpResponse('{"status":"success"}',content_type='application/json')
        else:
            return HttpResponse('{"status":"fail","msg":u"添加出错"}',content_type='application/json')


class OrgHomeView(View):
    def get(self,request,org_id):
        current_page = 'home'
        course_org=CourseOrg.objects.get(id=int(org_id))
        fav_has=False
        if request.user.is_authenticated():
           if UserFavorite.objects.filter(user=request.user, fav_id=course_org.id, fav_type=2):
               fav_has=True

        all_courses=course_org.course_set.all()[:3]
        all_teachers=course_org.teacher_set.all()[:1]
        desc=course_org.desc
        org_name=course_org.name
        return  render(request,'org-detail-homepage.html',{
                'all_courses':all_courses,
                'all_teachers':all_teachers,
                'desc':desc,
                'org_name':org_name,
                'course_org':course_org,
                'current_page': current_page,
                'fav_has':fav_has
        })



class OrgCourseView(View):
    def get(self,request,org_id):
        current_page='course'
        course_org=CourseOrg.objects.get(id=int(org_id))
        all_courses=course_org.course_set.all()
        return  render(request,'org-detail-course.html',{
                'all_courses':all_courses,
                'course_org':course_org,
                'current_page':current_page
        })



class OrgDescView(View):
    def get(self,request,org_id):
        current_page='desc'
        course_org=CourseOrg.objects.get(id=int(org_id))
        return  render(request,'org-detail-desc.html',{
                'course_org':course_org,
                'current_page':current_page
        })




class OrgTeacherView(View):
    def get(self,request,org_id):
        current_page = 'teacher'
        course_org=CourseOrg.objects.get(id=int(org_id))
        all_teachers=course_org.teacher_set.all()
        return  render(request,'org-detail-teachers.html',{
                'all_teachers':all_teachers,
                'course_org':course_org,
                'current_page': current_page
        })


class FavView(View):
    """
    收藏功能
    """
    def post(self,request):
        fav_id=request.POST.get('fav_id','0')
        fav_type=request.POST.get('fav_type','')
        #判断用户是否登陆
        if not request.user.is_authenticated():
            return HttpResponse('{"status":"fail","msg":u"用户未登陆"}', content_type='application/json')
        exist_records=UserFavorite.objects.filter(user=request,fav_id=int(fav_id),fav_type=int(fav_type))
        if exist_records:
            #已经收藏，取消
            exist_records.delete()
            return HttpResponse('{"status":"fail","msg":u"收藏"}', content_type='application/json')

        else:
            user_fav=UserFavorite()
            if int(fav_id)>0 and int(fav_type)>0:
                user_fav.fav_id=int(fav_id)
                user_fav.fav_type=int(fav_type)
                user_fav.save()
                return HttpResponse('{"status":"fail","msg":u"已收藏"}', content_type='application/json')
            else:
                return HttpResponse('{"status":"fail","msg":u"收藏出错"}', content_type='application/json')


class TeacherListView(View):
    def get(self,request):
        all_teachers=Teacher.objects.all()
        # 点击量排序
        sort = request.GET.get('sort', '')
        if sort:
            if sort=='hot':
                all_teachers = all_teachers.order_by('-click_nums')
        sorted_teacher=Teacher.objects.all().order_by('-click_nums')[:3]
        # 课程机构分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(all_teachers, 1, request=request)
        teachers = p.page(page)
        return render(request,'teachers-list.html',{
            'all_teachers':teachers,
            'sorted_teacher':sorted_teacher,
            'sort':sort
        })


class TeacherDetailView(View):
    def get(self,request,teacher_id):
        teacher=Teacher.objects.get(id=teacher_id)
        all_courses=Course.objects.filter(teachers=teacher)
        sorted_teacher = Teacher.objects.all().order_by('-click_nums')[:3]
        return render(request,'teacher-detail.html',{
            'teacher':teacher,
            'all_courses':all_courses,
            'sorted_teacher':sorted_teacher
        })

mxonline/MxOnlin/templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}慕学在线首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static  'css/style.css'%}">

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js'%}" type="text/javascript"></script>
    {% block custom_css %}{% endblock %}
</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">

                    <!--登录后跳转-->
                    {% if request.user.is_authenticated %}
                     <div class="top">
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png'%}"/></dd>
                                <dt><img width="20" height="20" src="/static/image/2016/12/default_big_14.png"/></dt>
                            </dl>
                        <div class="userdetail">
                            <dl>
                                <dt><img width="80" height="80" src="/static/image/2016/12/default_big_14.png"/></dt>
                                <dd>
                                    <h2>{{ user.username }}</h2>
                                    <p>{{ user.username }}</p>
                                </dd>
                            </dl>
                            <div class="btn">
                                <a class="personcenter fl" href="{% url 'users:user_list' %}">进入个人中心</a>
                                <a class="fr" href="{% url 'logout' %}">退出</a>
                            </div>
                        </div>
                    </div>

                        {% else %}
                          <div class="top">
                <div class="wp">
                    <div class="fl">
                        <p>服务电话：<b>33333333</b></p></div>
                    <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                </div>
                        <div class="wp">
                            <div class="fl">
                                <p>服务电话：<b>33333333</b></p>
                            </div>
                        </div>
                     </div>
                    {% endif %}
            </div>
            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="../images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="../images/search_btn.png"/>
                    </div>
                </div>
            </div>

			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li {% if request.path == '/' %}class="active"{% endif %} >
                                <a href="{% url 'index' %}">首页</a>
                            </li>
							<li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %} >
								<a href="{% url 'courses:course_list' %}">
									公开课<img class="hot" src="../images/nav_hot.png">
								</a>
							</li>
							<li {% if request.path|slice:'8' == '/teacher' %}class="active"{% endif %} >
								<a href="{% url 'teachers:teacher_list' %}">授课教师</a>
							</li>
							<li {% if request.path|slice:'4' == '/org' %}class="active"{% endif %} >
                                <a href="{% url 'org:org_list' %}">授课机构</a>
                            </li>
						</ul>
					</div>
				</div>
			</nav>
			</div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
{% endblock %}
{% block content %}
{% endblock %}
<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="../images/footlogo.png"/></a></li>
					<li class="code"><img src="../images/code.jpg"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="../images/tell.png"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="../js/plugins/laydate/laydate.js"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js'%}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
{% block custom_js %}

{% endblock %}
</body>
</html>

mxonline/MxOnlin/templates/course-list.html
{% extends 'base.html' %}
{% block title %}课程机构列表-慕学在线{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}

    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="{% if sort == '' %}active{% endif %}"><a href="?sort=">最新 </a></li>
						<li class="{% if sort == 'hot' %}active{% endif %}"><a href="?sort=hot">最热门</a></li>
						<li class="{% if sort == 'students' %}active{% endif %}"><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">

                        {% for course in all_courses.object_list %}
                            <div class="box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'courses:course_detail' course.id %}"><span class="fl">来自{{ course.course_org.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.fav_nums }}
                                    </span>
                                </div>
                            </div>
                        {% endfor %}
					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                {% if all_courses.has_previous %}
                    <li class="long"><a href="?{{ all_courses.previous_page_number.querystring }}" class="prev">上一页</a></li>
                {% endif %}
                {% for page in all_courses.pages %}
                    {% if page %}
                        {% ifequal page all_courses.number %}
                            <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="none"><a href="">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if all_courses.has_next %}
                    <li class="long"><a href="?{{ all_courses.next_page_number.querystring }}">下一页</a></li>
                {% endif %}
                        </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">

                    {% for hot_course in hot_courses %}
                         <dl>
						<dt>
							<a target="_blank" href="">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ hot_course.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2>{{ hot_course.name }}</h2></a>
							<span class="fl">难度：<i class="key">{{ hot_course.get_degree_display }}</i></span>
						</dd>
					</dl>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

mxonline/MxOnlin/templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% block title %}机构介绍{% endblock %}
{% block page_path %}机构介绍{% endblock %}
{% block right_form %}
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
            <p>{{ course_org.desc }}</p>

        </div>
    </div>
{% endblock %}

mxonline/MxOnlin/templates/teacher-detail.html
{% extends 'base.html' %}
{% block title %}课程讲师详情-慕学在线{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页></a>></li>
                <li href="{% url 'teachers:teacher_list' %}">授课讲师></li>
                <li>讲师详情</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}


    <section>
	<div class="wp butler-detail-box butler-diaryd-box clearfix">
        <div class="fl list">
            <div class="butler_detail_list clearfix">
                <div class="brief">
                    <dl class="des">
                        <dt>
                            <div class="picpic">
                                <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                            </div>
                            <div class="btn">
                                <span class="fl btn1 collectionbtn" id="jsLeftBtn">
                                     收藏
                                </span>
                                <span class="fr btn2 shareBtn bdsharebuttonbox"
                                      data-text="授课教师-李老师-慕学网"
                                      data-desc="我在#慕课网#发现了"
                                      data-comment="李老师，工作年限：5年；学历：本科；所在公司：阿里巴巴&nbsp;；经典案例：django入门和深入；flask入门"
                                      data-url="/diary/hk_detail/10/">
                                    <span class="fl">分享</span>
                                    <a href="#" class="bds_more" data-cmd="more"></a>
                                </span>
                            </div>
                        </dt>
                        <dd>
                            <a href="/diary/hk_detail/10/">
                                <h1>bobby<span class="key picbig">{{ teacher.name }}</span></h1>
                            </a>
                            <ul class="cont">
                                <li>工作年限：<span>{{ teacher.work_year }}年</span></li>
                                <li>就职公司：<span>{{ teacher.work_company }}</span></li>
                                <li>工作职位：<span>{{ teacher.work_position }}&nbsp;</span></li>
                                <li>教学特点：<span>{{ teacher.points }}</span></li>
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="butler_detail_cont clearfix">
                <div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active"><a href="/diary/hk_detail/10/">全部课程</a> </li>
					</ul>
				</div>
                    <div class="companycenter">
                        <div class="group_list brief">

                            {% for course in all_courses %}
                                 <div class="module1_5 box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}"><h2>d{{ course.name }}</h2></a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl">{{ course.course_org.name }}</span>
                                    <span class="star fr  notlogin" data-favid="15">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                            {% endfor %}


                        </div>
                    </div>
                <!--<div class="pageturn">-->
                    <!--<ul class="pagelist">-->
                        <!--<li class="active"><a href="?page=1">1</a></li>-->
                    <!--</ul>-->
                <!--</div>-->
            </div>
            </div>
        </div>
        <div class="fr list">
             <div class="butler_detail_list">
                <div class="right butler-company-box">
                <div class="head">
                    <h1>{{ teacher.org.name }}</h1>
                    <p>知名高校，权威教学</p>
                </div>
                <div class="pic">
                    <a href="org-detail-homepage.html">
                        <img width="150" height="80" src="../media/org/2016/11/imooc.png"/>
                    </a>
                </div>
                <a href="{% url 'org:org_home' teacher.org.id%}">
                    <h2 class="center">{{ teacher.org.name }}</h2>
                </a>
                <p class="center tell">地址：{{ teacher.org.address }}</p>
                <a class="btn" id="jsRightBtn">收藏</a>
            </div>
            </div>
            <div class="butler_detail_cont">
                <div class="butler_list_box">
                    <div class="right layout">
                        <div class="head">讲师排行榜</div>

                   {% for sort_teacher in sorted_teacher %}

                        <dl class="des">
                            <span class="num fl">1</span>
                            <a href="{% url 'teachers:teacher_detail' sort_teacher.id %}/">
                                <dt>
                                    <img width="50" height="50" class="scrollLoading" src="{{ MEDIA_URL }}{{ sort_teacher.image }}"/>
                                </dt>
                            </a>
                            <dd>
                                <a href="{% url 'teachers:teacher_detail' sort_teacher.id %}">
                                    <h1 title="bobby">{{ sort_teacher.name}}</h1>
                                </a>
                                <p>工作年限：<span>{{ sort_teacher.work_year }}年</span></p>
                            </dd>
                        </dl>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
	</div>
</section>
{#    {% block custom_js %}#}
{#        <script type="text/javascript">#}
{#//收藏分享#}
{#function add_fav(current_elem, fav_id, fav_type){#}
{#    $.ajax({#}
{#        cache: false,#}
{#        type: "POST",#}
{#        url:"{% url 'organization:fav' %}",#}
{#        data:{'fav_id':fav_id, 'fav_type':fav_type},#}
{#        async: true,#}
{#        beforeSend:function(xhr, settings){#}
{#            xhr.setRequestHeader("X-CSRFToken",'csrf_token');#}
{#        },#}
{#        success: function(data) {#}
{#            if(data.status == 'fail'){#}
{#                if(data.msg == '用户未登陆'){#}
{#                    window.location.href="login.html";#}
{#                }else{#}
{#                    alert(data.msg)#}
{#                }#}
{##}
{#            }else if(data.status == 'success'){#}
{#                current_elem.text(data.msg)#}
{#            }#}
{#        },#}
{#    });#}
{#}#}
{##}
{#$('#jsLeftBtn').on('click', function(){#}
{#    add_fav($(this), {{ teacher.id }}, 3);#}
{#});#}
{##}
{#$('#jsRightBtn').on('click', function(){#}
{#    add_fav($(this), {{ teacher.org.id }}, 2);#}
{#});#}
{##}
{##}
{#</script>#}
{#        {% endblock %}#}
{% endblock %}